name: sales-forecasting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - cpuonly=2.0
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - openpyxl
  - pyyaml
  - ipykernel
  - pip
  - pip:
      - python-dotenv
